all:
  children:
    k3s_master:
      hosts:
        k3s_test_node:
          ansible_host: 213.171.8.240 # timeweb doesn't support dynamic environments out of the box, so it is static(but it is possible to write a plugin)
