name: Ansible Playbook CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Setup ansible
        run: |
          python -m pip install --upgrade pip
          pip install "ansible>=8.0.0"

      - name: Prepare SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run playbook (support-tools)
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          echo "$ANSIBLE_VAULT_PASSWORD" > ~/.vault_pass.txt
          ansible-playbook site.yml --tags support-tools --vault-password-file ~/.vault_pass.txt
        
      - name: Run playbook (nginx-conf)
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          echo "$ANSIBLE_VAULT_PASSWORD" > ~/.vault_pass.txt
          ansible-playbook site.yml --tags nginx,conf --vault-password-file ~/.vault_pass.txt
